/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogodavelha;

import Util.Req;
import Util.Resp;
import java.awt.Color;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author rick
 */
public class tela extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    
    int porta = 54321;
    String ip = "127.0.0.1";
    Socket socket;
    ObjectOutputStream out;
    ObjectInputStream in;
    
    
    public tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(85, 171, 178));
        setForeground(new java.awt.Color(153, 102, 0));

        jButton1.setText(".");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(".");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(".");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(".");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(".");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText(".");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(".");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText(".");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText(".");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel1.setText("Vitórias Jogador:");

        jButton11.setText("Resetar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel2.setText(".");

        jLabel3.setText("Vitórias Computador:");

        jLabel4.setText(".");

        jButton12.setText("< Voltar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton11))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String checarTexto = jButton2.getText();

        if (checarTexto == "X" || checarTexto == "O") {
            JOptionPane.showMessageDialog(null, "Campo já selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);;
        } else {
        jogodavelha.JogoDaVelhaMain.arr.get(0).set(1, 1);
        System.out.println(jogodavelha.JogoDaVelhaMain.arr);
        jButton2.setText("X");
        ServerPlay(0, 1);
        jLabel2.setText(""+jogodavelha.JogoDaVelhaMain.playerWins);
        jLabel4.setText(""+jogodavelha.JogoDaVelhaMain.computerWins);

        }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1x1
        String checarTexto = jButton1.getText();

        if (checarTexto == "X" || checarTexto == "O") {
            JOptionPane.showMessageDialog(null, "Campo já selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);;
        } else {
        jogodavelha.JogoDaVelhaMain.arr.get(0).set(0, 1);
        System.out.println(jogodavelha.JogoDaVelhaMain.arr);
        jButton1.setText("X");
 //       jogodavelhateste.JogoDaVelhaTeste.checkBoard1x1();
        ServerPlay(0, 0);
        jLabel2.setText(""+jogodavelha.JogoDaVelhaMain.playerWins);
        jLabel4.setText(""+jogodavelha.JogoDaVelhaMain.computerWins);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String checarTexto = jButton3.getText();

        if (checarTexto == "X" || checarTexto == "O") {
            JOptionPane.showMessageDialog(null, "Campo já selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);;
        } else {
        jogodavelha.JogoDaVelhaMain.arr.get(0).set(2, 1);
        System.out.println(jogodavelha.JogoDaVelhaMain.arr);
        jButton3.setText("X");
//        jogodavelhateste.JogoDaVelhaTeste.checkBoard1x1();
        ServerPlay(0, 2);
        jLabel2.setText(""+jogodavelha.JogoDaVelhaMain.playerWins);
        jLabel4.setText(""+jogodavelha.JogoDaVelhaMain.computerWins);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String checarTexto = jButton4.getText();

        if (checarTexto == "X" || checarTexto == "O") {
            JOptionPane.showMessageDialog(null, "Campo já selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);;
        } else {
        jogodavelha.JogoDaVelhaMain.arr.get(1).set(0, 1);
        System.out.println(jogodavelha.JogoDaVelhaMain.arr);
        jButton4.setText("X");
//        jogodavelhateste.JogoDaVelhaTeste.checkBoard1x1();
        ServerPlay(1, 0);
        jLabel2.setText(""+jogodavelha.JogoDaVelhaMain.playerWins);
        jLabel4.setText(""+jogodavelha.JogoDaVelhaMain.computerWins);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String checarTexto = jButton5.getText();

        if (checarTexto == "X" || checarTexto == "O") {
            JOptionPane.showMessageDialog(null, "Campo já selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);;
        } else {        
        jogodavelha.JogoDaVelhaMain.arr.get(1).set(1, 1);
        System.out.println(jogodavelha.JogoDaVelhaMain.arr);
        jButton5.setText("X");
//        jogodavelhateste.JogoDaVelhaTeste.checkBoard1x1();
        ServerPlay(1, 1);
        jLabel2.setText(""+jogodavelha.JogoDaVelhaMain.playerWins);
        jLabel4.setText(""+jogodavelha.JogoDaVelhaMain.computerWins);

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String checarTexto = jButton6.getText();

        if (checarTexto == "X" || checarTexto == "O") {
            JOptionPane.showMessageDialog(null, "Campo já selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);;
        } else {
        jogodavelha.JogoDaVelhaMain.arr.get(1).set(2, 1);
        System.out.println(jogodavelha.JogoDaVelhaMain.arr);
        jButton6.setText("X");
//       jogodavelhateste.JogoDaVelhaTeste.checkBoard1x1();
        ServerPlay(1, 2);
        jLabel2.setText(""+jogodavelha.JogoDaVelhaMain.playerWins);
        jLabel4.setText(""+jogodavelha.JogoDaVelhaMain.computerWins);

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String checarTexto = jButton7.getText();

        if (checarTexto == "X" || checarTexto == "O") {
            JOptionPane.showMessageDialog(null, "Campo já selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);;
        } else {        
        jogodavelha.JogoDaVelhaMain.arr.get(2).set(0, 1);
        System.out.println(jogodavelha.JogoDaVelhaMain.arr);
        jButton7.setText("X");
//       jogodavelhateste.JogoDaVelhaTeste.checkBoard1x1();
        ServerPlay(2, 0);
        jLabel2.setText(""+jogodavelha.JogoDaVelhaMain.playerWins);
        jLabel4.setText(""+jogodavelha.JogoDaVelhaMain.computerWins);

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String checarTexto = jButton8.getText();

        if (checarTexto == "X" || checarTexto == "O") {
            JOptionPane.showMessageDialog(null, "Campo já selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);;
        } else {        
        jogodavelha.JogoDaVelhaMain.arr.get(2).set(1, 1);
        System.out.println(jogodavelha.JogoDaVelhaMain.arr);
        jButton8.setText("X");
//        jogodavelhateste.JogoDaVelhaTeste.checkBoard1x1();
        ServerPlay(2, 1);
        jLabel2.setText(""+jogodavelha.JogoDaVelhaMain.playerWins);
        jLabel4.setText(""+jogodavelha.JogoDaVelhaMain.computerWins);

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String checarTexto = jButton9.getText();

        if (checarTexto == "X" || checarTexto == "O") {
            JOptionPane.showMessageDialog(null, "Campo já selecionado", "Aviso", JOptionPane.WARNING_MESSAGE);;
        } else {        
        jogodavelha.JogoDaVelhaMain.arr.get(2).set(2, 1);
        System.out.println(jogodavelha.JogoDaVelhaMain.arr);
        jButton9.setText("X");
//        jogodavelhateste.JogoDaVelhaTeste.checkBoard1x1();
        ServerPlay(2, 2);
        jLabel2.setText(""+jogodavelha.JogoDaVelhaMain.playerWins);
        jLabel4.setText(""+jogodavelha.JogoDaVelhaMain.computerWins);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    public void ServerPlay(int row, int col) {
        
        Boolean draw = JogoDaVelhaMain.estaCheio(JogoDaVelhaMain.arr);

        if (draw == true) {
            JOptionPane.showMessageDialog(null, "Empate, você conseguiu perder para um computador 🫠", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

    
        try {
            // o cliente está pedindo conexão com o servidor que está no IP e Porta informados
            socket = new Socket(Client.Client.ip, Client.Client.porta);
            System.out.println("Conectado com o servidor.");
//            jLabel1.setText("Vez do Computador");
        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
            return;
        }
        
        try {
            
            Thread.sleep(3000);  
            out = new ObjectOutputStream(socket.getOutputStream());
            in = new ObjectInputStream(socket.getInputStream());
            int valor2 = 1;
            Req request = new Req(valor2, row, col, false);

            out.writeObject(request);   
            
            Resp response = (Resp) in.readObject();
            
            jogodavelha.JogoDaVelhaMain.arr.get(response.getRowIndex()).set(response.getColIndex(), response.getPcOperator());
            // DEBUG: Servidor checa o tabuleiro.
            jogodavelha.JogoDaVelhaMain.checkBoard1x1();

                        
            if (response.getRowIndex() == 0 && response.getColIndex() == 0) {
                jButton1.setText("O");
            } else if (response.getRowIndex() == 0 && response.getColIndex() == 1) {
                jButton2.setText("O");
            } else if (response.getRowIndex() == 0 && response.getColIndex() == 2) {
                jButton3.setText("O");
            } else if (response.getRowIndex() == 1 && response.getColIndex() == 0) {
                jButton4.setText("O");
            } else if (response.getRowIndex() == 1 && response.getColIndex() == 1) {
                jButton5.setText("O");
            } else if (response.getRowIndex() == 1 && response.getColIndex() == 2) {
                jButton6.setText("O");
            } else if (response.getRowIndex() == 2 && response.getColIndex() == 0) {
                jButton7.setText("O");
            } else if (response.getRowIndex() == 2 && response.getColIndex() == 1) {
                jButton8.setText("O");
            } else if (response.getRowIndex() == 2 && response.getColIndex() == 2) {
                jButton9.setText("O");
            }

            System.out.println("Response" + response.getRowIndex() + response.getColIndex());

        } catch (Exception e) {
            System.out.println("Erro na comunicação: " + e.getMessage());
        }
    }
    
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jogodavelha.JogoDaVelhaMain.arrayServer.clear();
        try {
            // o cliente está pedindo conexão com o servidor que está no IP e Porta informados
            socket = new Socket(Client.Client.ip, Client.Client.porta);
            System.out.println("Conectado com o servidor.");
//            jLabel1.setText("Vez do Computador");
        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
            return;
        }
        
        try {
            
            Thread.sleep(3000);
            
            out = new ObjectOutputStream(socket.getOutputStream());
            in = new ObjectInputStream(socket.getInputStream());

            Req request = new Req(0, -2, -2, true);

            out.writeObject(request);   
      
        } catch (Exception e) {
            System.out.println("Erro na comunicação: " + e.getMessage());
        }
        for (ArrayList<Integer> row :  jogodavelha.JogoDaVelhaMain.arr) {
         row.clear();
        for (int j = 0; j < 3; j++) {
            row.add(0);
        }
    }
        
      
        jButton1.setText(".");
        jButton2.setText(".");
        jButton3.setText(".");
        jButton4.setText(".");
        jButton5.setText(".");
        jButton6.setText(".");
        jButton7.setText(".");
        jButton8.setText(".");
        jButton9.setText(".");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        tela.super.setVisible(false);
        ChooseGameScreen telaHome = new ChooseGameScreen();
        telaHome.getContentPane().setBackground( Color.lightGray );
        telaHome.setLocationRelativeTo(null);
        telaHome.setSize(500, 400);
        telaHome.setResizable(false);
        telaHome.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
